source 'https://rubygems.org'

ruby '2.2.3'

gem 'rack', '~> 1.5.2'
gem 'puma'
gem 'grape', '~> 0.10.0'
gem 'activerecord', '~> 4.1.6', require: 'active_record'
gem 'grape-activerecord'
gem 'pg'
gem 'rake'
gem 'pry'
gem 'kaminari', '>= 0.17.0', :require => 'kaminari/grape'
gem 'rack-cors', :require => 'rack/cors'
gem 'grape-active_model_serializers', '>= 1.4.0'
