source 'https://rubygems.org'

ruby '2.2.3'

gem 'rack', '~> 2.1.3'
gem 'puma', '>= 2.12.0'
gem 'grape', '~> 0.9.0'
gem 'activerecord', '~> 4.1.6', require: 'active_record'
gem 'grape-activerecord', '>= 2.0.0'
gem 'pg'
gem 'rake'
gem 'pry'
gem 'kaminari', '>= 0.16.3', :require => 'kaminari/grape'
gem 'rack-cors', :require => 'rack/cors'
gem 'grape-active_model_serializers', '>= 1.3.2'
