source 'https://rubygems.org'

ruby '2.2.3'

gem 'rack', '~> 1.5.2'
gem 'puma'
gem 'grape', '~> 0.9.0'
gem 'activerecord', '4.2.8'
gem 'grape-activerecord', '>= 2.0.0'
gem 'pg'
gem 'rake'
gem 'pry'
gem 'kaminari', '>= 0.16.3'
gem 'rack-cors', :require => 'rack/cors'
gem 'grape-active_model_serializers', '>= 1.3.2'
